site_name: NeSI FlexiHPC

nav:
  - Home: 'index.md'
  - 'User Guides':
    - 'User Guides': user-guide/index.md
    - 'Launch and mange instances':
        - 'Launch and mange instances': user-guide/launch-and-mange-instances/index.md
        - 'With the Dashboard':
          - 'Launch an Instance via the Dashboard': user-guide/launch-and-mange-instances/launch-an-instance-via-dashboard.md
          - 'Resizing an Instance via the Dashboard': user-guide/launch-and-mange-instances/resizing-an-Instance-via-the-dashboard.md
          - 'Manage Floating IPs via the Dashboard': user-guide/launch-and-mange-instances/manage-floating-ips-via-the-dashboard.md
        - 'With the CLI':
          - 'Launch an Instance via CLI': user-guide/launch-and-mange-instances/launch-an-instance-via-cli.md
          - 'Launch an Instance from an Image': user-guide/launch-and-mange-instances/launch-an-instance-from-an-image.md
          - 'Launch an Instance from a Volume': user-guide/launch-and-mange-instances/launch-an-instance-from-a-volume.md
          - 'Resizing an Instance via CLI': user-guide/launch-and-mange-instances/resizing-an-Instance-via-cli.md
          - 'Manage Floating IPs via CLI': user-guide/launch-and-mange-instances/manage-floating-ips-via-cli.md
        - 'Other Tools':
          - 'Deploy with Terraform': user-guide/launch-and-mange-instances/deployment-of-an-instance-with-terraform.md
    - 'Setting up your CLI Environment': user-guide/setting-up-your-CLI-environment/setting-up-your-cli-environment.md
  # - About:
  #   - 'License': 'license.md'
  #   - 'Release Notes': 'release-notes.md'

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - glightbox
  - search